### ISSUE TITLE
All queries fail at the same skip token

### ISSUE THREAD

**Issue by patrickleclair-GORDONFN** [gordonfn/api#10] opened 2022-02-11 13:31 UTC
Hi Patrick, 

unfortunately reinstallation does not help. The query is aborted after some successful partial queries with the response$status_code error. Small queries like the first 1000 pH values go through without problems but larger queries do not. It’s interesting that they always get aborted after the same “skipped token”: For example it is skiptoken=Id%3A4395504 for querying all Platinum samples. Could it be that token are queried which do not (no longer) exist?

Best

Annika

**Comment by willfarrell** [comment] 2022-04-30 04:05
Duplicate of https://github.com/gordonfn/api/issues/9

**Closed as completed by willfarrell** 2022-04-30 04:05 UTC
Labels: bug
